from enum import Enum


class RequestPayloadCode(Enum):
    REQUEST_REGISTRATION = 1025
    REQUEST_PUBLIC_KEY = 1026
    REQUEST_RE_CONNECT = 1027
    REQUEST_SEND_FILE = 1028
    REQUEST_CRC_VALID = 1029
    REQUEST_CRC_NOT_VALID_RE_SEND = 1030
    REQUEST_CRC_NOT_VALID_STOP = 1031


