from enum import Enum


class ResponsePayloadCode(Enum):
    RESPONSE_REGISTER_SUCCESS = 1600
    RESPONSE_REGISTER_FAIL = 1601
    RESPONSE_RECEIVED_PUBLIC_KEY = 1602
    RESPONSE_FILE_RECEIVED_WITH_VALID_CRC = 1603
    RESPONSE_MSG_RECEIVED = 1604
    RESPONSE_RE_CONNECT_ACCEPTED = 1605
    RESPONSE_RE_CONNECT_DENIED = 1606
    RESPONSE_ERROR = 1607
